#! /bin/sh

install()
{
	cp meego-ux-mediafsd /usr/bin/
	mkdir -p /usr/lib/meego-ux-mediafs/readers
	cp libplugin-*.so /usr/lib/meego-ux-mediafs/readers/

	cp meego-ux-mediafs /etc/init.d/

	for i in 0 1 2 6; do
		cd /etc/rc$i.d
		ln -s ../init.d/meego-ux-mediafs ./K76meego-ux-mediafs
	done

	for i in 3 4 5; do
		cd /etc/rc$i.d
		ln -s ../init.d/meego-ux-mediafs ./S26meego-ux-mediafs
	done

	if [ ! -f meego-ux-mediafs.conf ]; then
cat <<EOF >meego-ux-mediafs.conf
square		ratio=1.00 crop=centre maxwidth_px=128 maxheight_px=128
preview		maxwidth_px=512 maxheight_px=512
EOF
	fi
	mv meego-ux-mediafs.conf /etc/

	chkconfig --add meego-ux-mediafs
}

uninstall()
{
	chkconfig --del meego-ux-mediafs >/dev/null 2>&1
	if [ -f /etc/init.d/meego-ux-mediafs ]; then
		/etc/init.d/meego-ux-mediafs stop
		/etc/init.d/meego-ux-mediafs restore
	fi
	rm -f /usr/bin/meego-ux-mediafsd >/dev/null 2>&1
	rm -f /etc/init.d/meego-ux-mediafs >/dev/null 2>&1
	rm -f /etc/rc1.d/S26meego-ux-mediafs >/dev/null 2>&1
	for i in 0 2 3 4 5 6; do
		rm -f /etc/rc$i.d/K76meego-ux-mediafs >/dev/null 2>&1
	done
	rm -rf /usr/lib/meego-ux-mediafs/readers
	rm -f /etc/meego-ux-mediafs.conf >/dev/null 2>&1
}

case "$1" in
	install)
		uninstall
		echo "Installing meego-ux-mediafs"
		install
		echo "Finished"
		echo "Start with \`/etc/init.d/meego-ux-mediafs start' or reboot"
		;;
	uninstall)
		echo "Removing meego-ux-mediafs"
		uninstall
		;;
	*)
		echo "Usage: $0 {install|uninstall}"
		exit 1
		;;
esac
