#! /bin/bash
#
# Init file for MeeGo thumbnailer daemon
#
# chkconfig: 345 26 76
# description: Loads indexer and thumbnailer service

. /etc/init.d/functions

MANAGED_DIRS=(Documents Downloads Pictures Public Templates Videos)
HOME_USER=meego
HOME_DIR=/home/$HOME_USER
PLUGINS_DIR=/usr/lib/meego-ux-mediafs
CONFIG=/etc/meego-ux-mediafs.conf
MEDIAFSD_DIR="$HOME_DIR/.mediafs-mount"

has_fuse_mount()
{
	mount | grep -q " on $1 type fuse."
}

has_bind_mount()
{
	mount | grep -q " on $1 type none (rw,bind)"
}

start_dir()
{
	local dir="$dir"
	if ! test -d "$MEDIAFSD_DIR/$dir"; then
		if ! mkdir "$MEDIAFSD_DIR/$dir"; then
			failure "Mediafs mount directory creation: $dir"
			return 1
		fi
		if ! chown $HOME_USER:$HOME_USER "$MEDIAFSD_DIR/$dir"; then
			failure "Mediafs mount directory permissions: $dir"
		fi
		success "Mediafs mount directory creation"
	fi

	if ! has_bind_mount "$MEDIAFSD_DIR/$dir"; then
		if ! mount -o bind,rw "$HOME_DIR/$dir" \
				"$MEDIAFSD_DIR/$dir"; then
			failure "Mount mediafs directory: $dir"
			return 1
		fi
	fi

	if ! has_fuse_mount "$HOME_DIR/$dir"; then
		if ! su - $HOME_USER -c "meego-ux-mediafsd \
				-c '$CONFIG' -p '$PLUGINS_DIR' \
				-s '$MEDIAFSD_DIR/$dir' \
				-m '$HOME_DIR/$dir' \
				-t '$HOME_DIR/.thumbnails' >/dev/null"; then
			failure "Mediafs mount: $dir"
			return 1
		fi
	fi
	return 0
}

stop_dir()
{
	local dir="$dir"
	local ret=0
	if has_fuse_mount "$HOME_DIR/$dir"; then
		fusermount -u "$HOME_DIR/$dir"
		ret=1
	fi
	if has_bind_mount "$MEDIAFSD_DIR/$dir"; then
		umount "$MEDIAFSD_DIR/$dir"
		ret=1
	fi
	return $ret
}


start()
{
	which meego-ux-mediafsd &>/dev/null || exit 1

	if ! lsmod | grep -qw fuse; then
		echo -n $"Loading FUSE module: "
		if ! modprobe fuse >/dev/null 2>&1; then
			failure $"FUSE module loading"
			exit 1
		else
			success $"FUSE module loading"
		fi
	fi

	if ! test -d "$MEDIAFSD_DIR"; then
		action "Mediafs directory generation" \
				mkdir "$MEDIAFSD_DIR"
		action "Mediafs directory permissions" \
				chown $HOME_USER:$HOME_USER \
				"$MEDIAFSD_DIR"
	fi

	# TODO read directories from config
	mkdir $HOME_DIR/.thumbnails >/dev/null 2>&1
	mkdir $HOME_DIR/.thumbnails/preview >/dev/null 2>&1
	mkdir $HOME_DIR/.thumbnails/square >/dev/null 2>&1
	mkdir $HOME_DIR/.thumbnails/rectangle >/dev/null 2>&1
	mkdir $HOME_DIR/.thumbnails/fullscreen >/dev/null 2>&1
	chown -R $HOME_USER:$HOME_USER $HOME_DIR/.thumbnails

	shopt -s dotglob

	echo -n $"Starting thumbnailing service: "
	local ret=0
	for dir in "${MANAGED_DIRS[@]}"; do
		has_fuse_mount "$HOME_DIR/$dir" && continue
		echo -n "$dir "
		if ! start_dir "$dir"; then
			ret=1
			stop_dir "$dir"
		fi
	done
	test $ret -eq 0 && success || failure
	echo

	return $ret
}

stop()
{
	echo -n $"Stopping thumbnailing service: "
	local ret=0
	for dir in "${MANAGED_DIRS[@]}"; do
		echo -n "$dir "
		stop_dir "$dir"
	done
	test $ret -eq 0 && success || failure
	echo

	# FIXME do we want to unload fuse module too?
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload)
		stop
		start
		;;
	status)
		#if ! ps -e | grep -qw media-preproces; then
		#	echo "meego-ux-mediafs is running"
		#else
		#	echo "meego-ux-mediafs is NOT running"
		#fi
		;;
	*)
		echo "Usage: $0 {start|stop|reload|status}"
		exit 1
		;;
esac

exit 0

